config/routes.rb
Rails.application.routes.draw do
  resources :smoothie_ingredients
  resources :ingredients, only: [:index, :create]
  resources :smoothies
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
end

app/models/smoothie.rb
class Smoothie < ApplicationRecord
  has_many :smoothie_ingredients
  has_many :ingredients, through: :smoothie_ingredients
end

app/models/smoothie_ingredient.rb
class SmoothieIngredient < ApplicationRecord
  belongs_to :smoothie
  belongs_to :ingredient 
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/ingredients_controller.rb
class IngredientsController < ApplicationController
  has_many :smoothie_ingredients
  has_many :smoothies, through: :smoothie_ingredients
end

app/controllers/smoothie_ingredients_controller.rb
class SmoothieIngredientsController < ApplicationController
end

app/controllers/smoothies_controller.rb
class SmoothiesController < ApplicationController

  def index
    @smoothies = Smoothie.all
  end

  def new
  end

  def create
  end

  def show
    @smoothie = Smoothie.find(params[:id])
    @ingredients = @smoothie.ingredients
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/ingredients_helper.rb
module IngredientsHelper
end

app/helpers/smoothie_ingredients_helper.rb
module SmoothieIngredientsHelper
end

app/helpers/smoothies_helper.rb
module SmoothiesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RootyTootyBlendyFruity</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/smoothies/index.html.erb
<h1> Here's all your smoothies </h1>

<% @smoothies.each do |smoothie| %>
  <%= link_to smoothie.name, smoothy_path(smoothie) %><br>
<%end %>

app/views/smoothies/show.html.erb
<h1> Here's your smoothie!</h1>


Name:<%= @smoothie.name %> <br>
<ul>
  <% @ingredients.each do |ing| %>
  <li><%= ing.name %></li><br>
<%end%>